apiVersion: apps/v1 
kind: Deployment 
metadata: 
name: webapp1 
spec: 
replicas: 2 
selector: 
matchLabels: 
app: webapp1 
template: 
metadata: 
labels: 
app: webapp1 
spec: 
containers: 
- name: webapp1 
image: apiVersion: apps/v1 
kind: Deployment 
metadata: 
name: webapp1 
spec: 
replicas: 2 
selector: 
matchLabels: 
app: webapp1 
template: 
metadata: 
labels: 
app: webapp1 
spec: 
containers: 
- name: webapp1 
image: vrvasanthkumar/kube8s:tagversion 
ports: 
- containerPort: 8080 
--- 
apiVersion: v1 
kind: Service 
metadata: 
name: webapp1-svc 
labels: 
app: webapp1 
spec: 
type: LoadBalancer
ports: 
- protocol: TCP 
port: 80 
targetPort: 8080 
selector: 
app: webapp1/kube8s:tagversion 
ports: 
- containerPort: 8080 
--- 
apiVersion: v1 
kind: Service 
metadata: 
name: webapp1-svc 
labels: 
app: webapp1 
spec: 
type: LoadBalancer
ports: 
- protocol: TCP 
port: 80 
targetPort: 8080 
selector: 
app: webapp1
