---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp1
 labels:
  app: myapp1
spec:
 replicas: 1 
 selector:
  matchLabels:
   app: myapp1
 template:
  metadata: 
   labels:
    app: myapp1
  spec:
   containers:
   - name: myapp1
     image: vrvasanthkumar/kube8s:tagversion
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp1
spec:
  type: LoadBalancer
  selector:
    app: myapp1
  ports:
    - protocol: TCP
      port: 6655
      targetPort: 8080
